server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  pattern:
    console: "%clr%d{HH:mm:ss} %blue([%-5level]) (%yellow(%c{1.}) - %msg%n)"
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true